// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TicketDbContext))]
    partial class TicketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Agents.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Agents", (string)null);
                });

            modelBuilder.Entity("Core.Agents.AgentSpecialization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IncidentCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SpecializationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IncidentCategoryId");

                    b.HasIndex("SpecializationId");

                    b.HasIndex(new[] { "AgentId", "SpecializationId" }, "UQ_AgentSpecializations_Agent_Specialization")
                        .IsUnique();

                    b.ToTable("AgentSpecializations", (string)null);
                });

            modelBuilder.Entity("Core.Agents.IncidentCategorySpecialization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SpecializationId")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SpecializationId");

                    b.HasIndex(new[] { "CategoryId", "SpecializationId" }, "UQ_IncidentCategorySpecializations_Category_Specialization")
                        .IsUnique();

                    b.ToTable("IncidentCategorySpecializations", (string)null);
                });

            modelBuilder.Entity("Core.Agents.Specialization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UQ_Specializations_Name")
                        .IsUnique();

                    b.ToTable("Specializations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Network"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Infrastructure"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Database"
                        });
                });

            modelBuilder.Entity("Core.Incidents.Categories.IncidentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RequiredSeniority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SpecializationMatchRule")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UQ_IncidentCategories_Name")
                        .IsUnique();

                    b.ToTable("IncidentCategories", (string)null);
                });

            modelBuilder.Entity("Core.Incidents.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedAgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IncidentSeverity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAgentId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ReporterId");

                    b.ToTable("Incidents", (string)null);
                });

            modelBuilder.Entity("Core.Incidents.Categories.NetworkIncident", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Symptom")
                        .HasColumnType("tinyint");

                    b.HasKey("CategoryId");

                    b.ToTable("NetworkIncidentCategories", (string)null);
                });

            modelBuilder.Entity("Core.Reporters.Reporter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(GETDATE())");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "XI_Reporters_UserId");

                    b.ToTable("Reporters", (string)null);
                });

            modelBuilder.Entity("Core.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Status");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("ConversationId")
                        .IsUnique();

                    b.HasIndex("IncidentId");

                    b.HasIndex("ReporterId");

                    b.HasIndex(new[] { "Lifecycle" }, "IX_Tickets_Status");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("Core.Tickets.Conversation.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReporterId");

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("Core.Tickets.Conversation.ConversationAgent", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConversationId", "AgentId");

                    b.HasIndex("AgentId");

                    b.ToTable("ConversationAgents", (string)null);
                });

            modelBuilder.Entity("Core.Tickets.Messages.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ParticipantId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("Core.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(GETDATE())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("_state")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("State");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserName" }, "IX_Users_UserName");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Core.Agents.Agent", b =>
                {
                    b.HasOne("Core.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("Core.Agents.Agent", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Agents.AgentSpecialization", b =>
                {
                    b.HasOne("Core.Agents.Agent", null)
                        .WithMany("Specializations")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Incidents.Categories.IncidentCategory", null)
                        .WithMany("RequiredSpecializations")
                        .HasForeignKey("IncidentCategoryId");

                    b.HasOne("Core.Agents.Specialization", null)
                        .WithMany()
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Agents.IncidentCategorySpecialization", b =>
                {
                    b.HasOne("Core.Incidents.Categories.IncidentCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Agents.Specialization", null)
                        .WithMany()
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Incidents.Incident", b =>
                {
                    b.HasOne("Core.Agents.Agent", null)
                        .WithMany("Incidents")
                        .HasForeignKey("AssignedAgentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Incidents.Categories.IncidentCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Reporters.Reporter", "Reporter")
                        .WithMany("Incidents")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Core.Incidents.IncidentSla", "IncidentSla", b1 =>
                        {
                            b1.Property<Guid>("IncidentId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("IncidentId");

                            b1.ToTable("Incidents");

                            b1.WithOwner()
                                .HasForeignKey("IncidentId");

                            b1.OwnsOne("Core.Incidents.IncidentDeadline", "Acknowledgement", b2 =>
                                {
                                    b2.Property<Guid>("IncidentSlaIncidentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<DateTime>("DueAt")
                                        .HasColumnType("datetime2")
                                        .HasColumnName("AckDueAt");

                                    b2.Property<long>("Duration")
                                        .HasColumnType("bigint")
                                        .HasColumnName("AckDuration");

                                    b2.HasKey("IncidentSlaIncidentId");

                                    b2.ToTable("Incidents");

                                    b2.WithOwner()
                                        .HasForeignKey("IncidentSlaIncidentId");
                                });

                            b1.OwnsOne("Core.Incidents.IncidentDeadline", "Resolution", b2 =>
                                {
                                    b2.Property<Guid>("IncidentSlaIncidentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<DateTime>("DueAt")
                                        .HasColumnType("datetime2")
                                        .HasColumnName("ResolutionDueAt");

                                    b2.Property<long>("Duration")
                                        .HasColumnType("bigint")
                                        .HasColumnName("ResolutionDuration");

                                    b2.HasKey("IncidentSlaIncidentId");

                                    b2.ToTable("Incidents");

                                    b2.WithOwner()
                                        .HasForeignKey("IncidentSlaIncidentId");
                                });

                            b1.Navigation("Acknowledgement")
                                .IsRequired();

                            b1.Navigation("Resolution")
                                .IsRequired();
                        });

                    b.Navigation("Category");

                    b.Navigation("IncidentSla")
                        .IsRequired();

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("Core.Incidents.Categories.NetworkIncident", b =>
                {
                    b.HasOne("Core.Incidents.Categories.IncidentCategory", "Category")
                        .WithOne()
                        .HasForeignKey("Core.Incidents.Categories.NetworkIncident", "CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Core.Reporters.Reporter", b =>
                {
                    b.HasOne("Core.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("Core.Reporters.Reporter", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Ticket", b =>
                {
                    b.HasOne("Core.Agents.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Tickets.Conversation.Conversation", "Conversation")
                        .WithOne()
                        .HasForeignKey("Core.Ticket", "ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Incidents.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Reporters.Reporter", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Conversation");

                    b.Navigation("Incident");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("Core.Tickets.Conversation.Conversation", b =>
                {
                    b.HasOne("Core.Reporters.Reporter", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("Core.Tickets.Conversation.ConversationAgent", b =>
                {
                    b.HasOne("Core.Agents.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Tickets.Conversation.Conversation", null)
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Tickets.Messages.Message", b =>
                {
                    b.HasOne("Core.Tickets.Conversation.Conversation", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Core.Tickets.Messages.MessageContent", "Content", b1 =>
                        {
                            b1.Property<Guid>("MessageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasMaxLength(5000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Body");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("Title");

                            b1.HasKey("MessageId");

                            b1.ToTable("Messages");

                            b1.WithOwner()
                                .HasForeignKey("MessageId");
                        });

                    b.Navigation("Content")
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Agents.Agent", b =>
                {
                    b.Navigation("Incidents");

                    b.Navigation("Specializations");
                });

            modelBuilder.Entity("Core.Incidents.Categories.IncidentCategory", b =>
                {
                    b.Navigation("RequiredSpecializations");
                });

            modelBuilder.Entity("Core.Reporters.Reporter", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("Core.Tickets.Conversation.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
